"""Official names, tiers and DLC - generated from the R2Wiki (risk-of-thunder/R2Wiki).

Sources: "Items and Equipments Data" and "Scene Names". Do not edit by hand: regenerate.
Format: code -> (in-game name, tier, DLC). Empty name = internal ID with no name (see identify.py).
"""
from __future__ import annotations

ITEM_INFO: dict[str, tuple[str, ...]] = {
    'AACannon': ('', 'No Tier', 'No DLC'),
    'AdaptiveArmor': ('', 'No Tier', 'No DLC'),
    'AlienHead': ('Alien Head', 'Red', 'No DLC'),
    'ArmorPlate': ('Repulsion Armor Plate', 'White', 'No DLC'),
    'ArmorReductionOnHit': ('Shattering Justice', 'Red', 'No DLC'),
    'ArtifactKey': ('Artifact Key', 'Boss', 'No DLC'),
    'AttackSpeedAndMoveSpeed': ('Mocha', 'White', 'Survivors of the Void'),
    'AttackSpeedOnCrit': ('Predatory Instincts', 'Green', 'No DLC'),
    'AttackSpeedPerNearbyAllyOrEnemy': ('Bolstering Lantern', 'White', 'Seekers of the Storm'),
    'AutoCastEquipment': ('Gesture of the Drowned', 'Lunar', 'No DLC'),
    'Bandolier': ('Bandolier', 'Green', 'No DLC'),
    'BarrageOnBoss': ('War Bonds', 'Red', 'Seekers of the Storm'),
    'BarrierOnCooldown': ('Eclipse Lite', 'White', 'Alloyed Collective'),
    'BarrierOnKill': ('Topaz Brooch', 'White', 'No DLC'),
    'BarrierOnOverHeal': ('Aegis', 'Red', 'No DLC'),
    'Bear': ('Tougher Times', 'White', 'No DLC'),
    'BearVoid': ('Safer Spaces', 'Void White', 'Survivors of the Void'),
    'BeetleGland': ("Queen's Gland", 'Boss', 'No DLC'),
    'Behemoth': ('Brilliant Behemoth', 'Red', 'No DLC'),
    'BleedOnHit': ('Tri-Tip Dagger', 'White', 'No DLC'),
    'BleedOnHitAndExplode': ('Shatterspleen', 'Boss', 'No DLC'),
    'BleedOnHitVoid': ('Needletick', 'Void White', 'Survivors of the Void'),
    'BonusGoldPackOnKill': ("Ghor's Tome", 'Green', 'No DLC'),
    'BonusHealthBoost': ('Quick Fix', 'No Tier', 'Alloyed Collective'),
    'BoostAllStats': ('Growth Nectar', 'Red', 'Seekers of the Storm'),
    'BoostAttackSpeed': ('', 'No Tier', 'No DLC'),
    'BoostDamage': ('', 'No Tier', 'No DLC'),
    'BoostEquipmentRecharge': ('', 'No Tier', 'No DLC'),
    'BoostHp': ('', 'No Tier', 'No DLC'),
    'BossDamageBonus': ('Armor-Piercing Rounds', 'White', 'No DLC'),
    'BounceNearby': ('Sentient Meat Hook', 'Red', 'No DLC'),
    'BurnNearby': ('', 'No Tier', 'No DLC'),
    'CaptainDefenseMatrix': ('Defensive Microbots', 'Red', 'No DLC'),
    'ChainLightning': ('Ukulele', 'Green', 'No DLC'),
    'ChainLightningVoid': ('Polylute', 'Void Green', 'Survivors of the Void'),
    'Clover': ('57 Leaf Clover', 'Red', 'No DLC'),
    'CloverVoid': ('Benthic Bloom', 'Void Red', 'Survivors of the Void'),
    'ConvertCritChanceToCritDamage': ('', 'No Tier', 'Survivors of the Void'),
    'CookedSteak': ('Seared Steak', 'No Tier', 'Alloyed Collective'),
    'CooldownOnCrit': ('Wicked Ring', 'No Tier', 'No DLC'),
    'CrippleWardOnLevel': ('', 'No Tier', 'No DLC'),
    'CritAtLowerElevation': ("Hiker's Boots", 'White', 'Alloyed Collective'),
    'CritDamage': ('Laser Scope', 'Red', 'Survivors of the Void'),
    'CritGlasses': ("Lens-Maker's Glasses", 'White', 'No DLC'),
    'CritGlassesVoid': ("Lost Seer's Lenses", 'Void White', 'Survivors of the Void'),
    'CritHeal': ('', 'No Tier', 'No DLC'),
    'Crowbar': ('Crowbar', 'White', 'No DLC'),
    'CutHp': ('', 'No Tier', 'No DLC'),
    'Dagger': ('Ceremonial Dagger', 'Red', 'No DLC'),
    'DeathMark': ('Death Mark', 'Green', 'No DLC'),
    'DelayedDamage': ('Warped Echo', 'White', 'Seekers of the Storm'),
    'DestructibleSpawner': ('', 'No Tier', 'Alloyed Collective'),
    'DrizzlePlayerHelper': ('', 'No Tier', 'No DLC'),
    'DroneDynamiteDisplay': ('', 'No Tier', 'Alloyed Collective'),
    'DroneUpgradeHidden': ('', 'No Tier', 'Alloyed Collective'),
    'DroneWeapons': ('Spare Drone Parts', 'Red', 'Survivors of the Void'),
    'DroneWeaponsBoost': ('', 'No Tier', 'Survivors of the Void'),
    'DroneWeaponsDisplay1': ('', 'No Tier', 'Survivors of the Void'),
    'DroneWeaponsDisplay2': ('', 'No Tier', 'Survivors of the Void'),
    'DronesDropDynamite': ('Box of Dynamite', 'Green', 'Alloyed Collective'),
    'Duplicator': ('Substandard Duplicator', 'Red', 'Alloyed Collective'),
    'ElementalRingVoid': ('Singularity Band', 'Void Green', 'Survivors of the Void'),
    'EmpowerAlways': ('', 'No Tier', 'Survivors of the Void'),
    'EnergizedOnEquipmentUse': ('War Horn', 'Green', 'No DLC'),
    'EquipmentMagazine': ('Fuel Cell', 'Green', 'No DLC'),
    'EquipmentMagazineVoid': ('Lysate Cell', 'Void Green', 'Survivors of the Void'),
    'ExecuteLowHealthElite': ('Old Guillotine', 'Green', 'No DLC'),
    'ExplodeOnDeath': ("Will-o'-the-wisp", 'Green', 'No DLC'),
    'ExplodeOnDeathVoid': ('Voidsent Flame', 'Void Green', 'Survivors of the Void'),
    'ExtraEquipment': ('Functional Coupler', 'Boss', 'Alloyed Collective'),
    'ExtraLife': ("Dio's Best Friend", 'Red', 'No DLC'),
    'ExtraLifeConsumed': ("Dio's Best Friend (Consumed)", 'No Tier', 'No DLC'),
    'ExtraLifeVoid': ('Pluripotent Larva', 'Void Red', 'Survivors of the Void'),
    'ExtraLifeVoidConsumed': ('Pluripotent Larva (Consumed)', 'No Tier', 'Survivors of the Void'),
    'ExtraShrineItem': ('Chance Doll', 'Green', 'Seekers of the Storm'),
    'ExtraStatsOnLevelUp': ('Prayer Beads', 'Green', 'Seekers of the Storm'),
    'FallBoots': ('H3AD-5T v2', 'Red', 'No DLC'),
    'Feather': ('Hopoo Feather', 'Green', 'No DLC'),
    'FireRing': ("Kjaro's Band", 'Green', 'No DLC'),
    'FireballsOnHit': ('Molten Perforator', 'Boss', 'No DLC'),
    'Firework': ('Bundle of Fireworks', 'White', 'No DLC'),
    'FlatHealth': ('Bison Steak', 'White', 'No DLC'),
    'FocusConvergence': ('Focused Convergence', 'Lunar', 'No DLC'),
    'FragileDamageBonus': ('Delicate Watch', 'White', 'Survivors of the Void'),
    'FragileDamageBonusConsumed': ('Delicate Watch (Broken)', 'No Tier', 'Survivors of the Void'),
    'FreeChest': ('Shipping Request Form', 'Green', 'Survivors of the Void'),
    'Ghost': ('', 'No Tier', 'No DLC'),
    'GhostOnKill': ('Happiest Mask', 'Red', 'No DLC'),
    'GoldOnHit': ('Brittle Crown', 'Lunar', 'No DLC'),
    'GoldOnHurt': ('Roll of Pennies', 'White', 'Survivors of the Void'),
    'GummyCloneIdentifier': ('', 'No Tier', 'No DLC'),
    'HalfAttackSpeedHalfCooldowns': ('Light Flux Pauldron', 'Lunar', 'Survivors of the Void'),
    'HalfSpeedDoubleHealth': ('Stone Flux Pauldron', 'Lunar', 'Survivors of the Void'),
    'HeadHunter': ('Wake of Vultures', 'Red', 'No DLC'),
    'HealOnCrit': ("Harvester's Scythe", 'Green', 'No DLC'),
    'HealWhileSafe': ('Cautious Slug', 'White', 'No DLC'),
    'HealingPotion': ('Power Elixir', 'White', 'Survivors of the Void'),
    'HealingPotionConsumed': ('Empty Bottle', 'No Tier', 'Survivors of the Void'),
    'HealthDecay': ('', 'No Tier', 'No DLC'),
    'Hoof': ("Paul's Goat Hoof", 'White', 'No DLC'),
    'IceRing': ("Runald's Band", 'Green', 'No DLC'),
    'Icicle': ('Frost Relic', 'Red', 'No DLC'),
    'IgniteOnKill': ('Gasoline', 'White', 'No DLC'),
    'ImmuneToDebuff': ("Ben's Raincoat", 'Red', 'Survivors of the Void'),
    'IncreaseDamageOnMultiKill': ('Chronic Expansion', 'White', 'Seekers of the Storm'),
    'IncreaseHealing': ('Rejuvenation Rack', 'Red', 'No DLC'),
    'IncreasePrimaryDamage': ('Luminous Shot', 'Green', 'Seekers of the Storm'),
    'Incubator': ('Ancestral Incubator', 'No Tier', 'No DLC'),
    'Infusion': ('Infusion', 'Green', 'No DLC'),
    'InvadingDoppelganger': ('', 'No Tier', 'No DLC'),
    'ItemDropChanceOnKill': ('Sonorous Whispers', 'Red', 'Seekers of the Storm'),
    'JumpBoost': ('Wax Quail', 'Green', 'No DLC'),
    'JumpDamageStrike': ('Faraday Spur', 'Green', 'Alloyed Collective'),
    'Junk': ('Junk', 'No Tier', 'No DLC'),
    'KillEliteFrenzy': ('Brainstalks', 'Red', 'No DLC'),
    'KnockBackHitEnemies': ('Breaching Fin', 'Green', 'Seekers of the Storm'),
    'Knurl': ('Titanic Knurl', 'Boss', 'No DLC'),
    'LaserTurbine': ('Resonance Disc', 'Red', 'No DLC'),
    'LemurianHarness': ('', 'No Tier', 'No DLC'),
    'LevelBonus': ('', 'No Tier', 'No DLC'),
    'LightningStrikeOnHit': ('Charged Perforator', 'Boss', 'No DLC'),
    'LowerPricedChests': ('Sale Star', 'Green', 'Seekers of the Storm'),
    'LowerPricedChestsConsumed': ('Sale Star (Consumed)', 'No Tier', 'Seekers of the Storm'),
    'LunarBadLuck': ('Purity', 'Lunar', 'No DLC'),
    'LunarDagger': ('Shaped Glass', 'Lunar', 'No DLC'),
    'LunarPrimaryReplacement': ('Visions of Heresy', 'Lunar', 'No DLC'),
    'LunarSecondaryReplacement': ('Hooks of Heresy', 'Lunar', 'No DLC'),
    'LunarSpecialReplacement': ('Essence of Heresy', 'Lunar', 'No DLC'),
    'LunarSun': ('Egocentrism', 'Lunar', 'Survivors of the Void'),
    'LunarTrinket': ('Beads of Fealty', 'Lunar', 'No DLC'),
    'LunarUtilityReplacement': ('Strides of Heresy', 'Lunar', 'No DLC'),
    'LunarWings': ('Blessings of Terafirmae', 'No Tier', 'Survivors of the Void'),
    'MageAttunement': ('', 'No Tier', 'No DLC'),
    'MasterBattery': ('Encrypted Cerebellum', 'Boss', 'Alloyed Collective'),
    'MasterCore': ('Exposed Cerebellum', 'Boss', 'Alloyed Collective'),
    'Medkit': ('Medkit', 'White', 'No DLC'),
    'MeteorAttackOnHighDamage': ('Runic Lens', 'Red', 'Seekers of the Storm'),
    'MinHealthPercentage': ('', 'No Tier', 'No DLC'),
    'MinionLeash': ('', 'No Tier', 'No DLC'),
    'MinorConstructOnKill': ('Defense Nucleus', 'Boss', 'Survivors of the Void'),
    'Missile': ('AtG Missile Mk. 1', 'Green', 'No DLC'),
    'MissileVoid': ('Plasma Shrimp', 'Void Green', 'Survivors of the Void'),
    'MoneyLoan': ('Ominous Loan Note', 'No Tier', 'Alloyed Collective'),
    'MonsoonPlayerHelper': ('', 'No Tier', 'No DLC'),
    'MonstersOnShrineUse': ('Defiant Gouge', 'Lunar', 'No DLC'),
    'MoreMissile': ('Pocket I.C.B.M.', 'Red', 'Survivors of the Void'),
    'MoveSpeedOnKill': ("Hunter's Harpoon", 'Green', 'Survivors of the Void'),
    'Mushroom': ('Bustling Fungus', 'White', 'No DLC'),
    'MushroomVoid': ('Weeping Fungus', 'Void White', 'Survivors of the Void'),
    'NearbyDamageBonus': ('Focus Crystal', 'White', 'No DLC'),
    'NovaOnHeal': ("N'kuhana's Opinion", 'Red', 'No DLC'),
    'NovaOnLowHealth': ('Genesis Loop', 'Boss', 'No DLC'),
    'OnLevelUpFreeUnlock': ('Longstanding Solitude', 'Lunar', 'Seekers of the Storm'),
    'OutOfCombatArmor': ('Oddly-shaped Opal', 'White', 'Survivors of the Void'),
    'ParentEgg': ('Planula', 'Boss', 'No DLC'),
    'Pearl': ('Pearl', 'Boss', 'No DLC'),
    'PermanentDebuffOnHit': ('Symbiotic Scorpion', 'Red', 'Survivors of the Void'),
    'PersonalShield': ('Personal Shield Generator', 'White', 'No DLC'),
    'Phasing': ('Old War Stealthkit', 'Green', 'No DLC'),
    'PhysicsProjectile': ('Orphaned Core', 'Red', 'Alloyed Collective'),
    'Plant': ('Interstellar Desk Plant', 'Red', 'No DLC'),
    'PlantOnHit': ('', 'No Tier', 'No DLC'),
    'PlasmaCore': ('', 'No Tier', 'No DLC'),
    'PowerCube': ('Prison Matrix', 'Boss', 'Alloyed Collective'),
    'PowerOrbSphere': ('Ocular Battery', 'No Tier', 'Alloyed Collective'),
    'PowerPyramid': ('Sentry Key', 'Boss', 'Alloyed Collective'),
    'PrimarySkillShuriken': ('Shuriken', 'Green', 'Survivors of the Void'),
    'RandomDamageZone': ('Mercurial Rachis', 'Lunar', 'No DLC'),
    'RandomEquipmentTrigger': ('Bottled Chaos', 'Red', 'Survivors of the Void'),
    'RandomlyLunar': ('Eulogy Zero', 'Lunar', 'Survivors of the Void'),
    'RegeneratingScrap': ('Regenerating Scrap', 'Green', 'Survivors of the Void'),
    'RegeneratingScrapConsumed': ('Regenerating Scrap (Consumed)', 'No Tier', 'Survivors of the Void'),
    'RepeatHeal': ('Corpsebloom', 'Lunar', 'No DLC'),
    'RoboBallBuddy': ('Empathy Cores', 'Boss', 'No DLC'),
    'ScrapGreen': ('Item Scrap, Green', 'Green', 'No DLC'),
    'ScrapGreenSuppressed': ('Strange Scrap, Green', 'No Tier', 'Survivors of the Void'),
    'ScrapRed': ('Item Scrap, Red', 'Red', 'No DLC'),
    'ScrapRedSuppressed': ('Strange Scrap, Red', 'No Tier', 'Survivors of the Void'),
    'ScrapWhite': ('Item Scrap, White', 'White', 'No DLC'),
    'ScrapWhiteSuppressed': ('Strange Scrap, White', 'No Tier', 'Survivors of the Void'),
    'ScrapYellow': ('Item Scrap, Yellow', 'Boss', 'No DLC'),
    'SecondarySkillMagazine': ('Backup Magazine', 'White', 'No DLC'),
    'Seed': ('Leeching Seed', 'Green', 'No DLC'),
    'SharedSuffering': ('Networked Suffering', 'Red', 'Alloyed Collective'),
    'ShieldBooster': ('Kinetic Dampener', 'Green', 'Alloyed Collective'),
    'ShieldOnly': ('Transcendence', 'Lunar', 'No DLC'),
    'ShinyPearl': ('Irradiant Pearl', 'Boss', 'No DLC'),
    'ShockDamageAura': ('Faulty Conductor', 'Boss', 'Alloyed Collective'),
    'ShockNearby': ('Unstable Tesla Coil', 'Red', 'No DLC'),
    'SiphonOnLowHealth': ('Mired Urn', 'Boss', 'No DLC'),
    'SkullCounter': ('Skull Token', 'No Tier', 'No DLC'),
    'SlowOnHit': ('Chronobauble', 'Green', 'No DLC'),
    'SlowOnHitVoid': ('Tentabauble', 'Void Green', 'Survivors of the Void'),
    'SpeedBoostPickup': ('Elusive Antlers', 'White', 'Seekers of the Storm'),
    'SpeedOnPickup': ("Collector's Compulsion", 'Green', 'Alloyed Collective'),
    'SprintArmor': ('Rose Buckler', 'Green', 'No DLC'),
    'SprintBonus': ('Energy Drink', 'White', 'No DLC'),
    'SprintOutOfCombat': ('Red Whip', 'Green', 'No DLC'),
    'SprintWisp': ('Little Disciple', 'Boss', 'No DLC'),
    'Squid': ('Squid Polyp', 'Green', 'No DLC'),
    'StatsFromScrap': ('', 'No Tier', 'Alloyed Collective'),
    'Stew': ('Hearty Stew', 'No Tier', 'Alloyed Collective'),
    'StickyBomb': ('Sticky Bomb', 'White', 'No DLC'),
    'StrengthenBurn': ('Ignition Tank', 'Green', 'Survivors of the Void'),
    'StunAndPierce': ('Electric Boomerang', 'Red', 'Seekers of the Storm'),
    'StunChanceOnHit': ('Stun Grenade', 'White', 'No DLC'),
    'Syringe': ("Soldier's Syringe", 'White', 'No DLC'),
    'TPHealingNova': ('Lepton Daisy', 'Green', 'No DLC'),
    'Talisman': ('Soulbound Catalyst', 'Red', 'No DLC'),
    'TeamSizeDamageBonus': ('', 'No Tier', 'No DLC'),
    'TeleportOnLowHealth': ('Unstable Transmitter', 'Green', 'Seekers of the Storm'),
    'TeleportOnLowHealthConsumed': ('Unstable Transmitter (Consumed)', 'No Tier', 'Seekers of the Storm'),
    'TeleportWhenOob': ('', 'No Tier', 'No DLC'),
    'TempestOnKill': ('', 'No Tier', 'No DLC'),
    'Thorns': ('Razorwire', 'Green', 'No DLC'),
    'TitanGoldDuringTP': ('Halcyon Seed', 'Boss', 'No DLC'),
    'TonicAffliction': ('Tonic Affliction', 'No Tier', 'No DLC'),
    'Tooth': ('Monster Tooth', 'White', 'No DLC'),
    'TransferDebuffOnHit': ('Neutronium Weight', 'Lunar', 'Alloyed Collective'),
    'TreasureCache': ('Rusted Key', 'White', 'No DLC'),
    'TreasureCacheVoid': ('Encrusted Key', 'Void White', 'Survivors of the Void'),
    'TriggerEnemyDebuffs': ('Noxious Thorn', 'Green', 'Seekers of the Storm'),
    'UltimateMeal': ('Ultimate Meal', 'No Tier', 'Alloyed Collective'),
    'UseAmbientLevel': ('', 'No Tier', 'No DLC'),
    'UtilitySkillMagazine': ('Hardlight Afterburner', 'Red', 'No DLC'),
    'VoidMegaCrabItem': ('Newly Hatched Zoea', 'Void Boss', 'Survivors of the Void'),
    'VoidmanPassiveItem': ('', 'No Tier', 'Survivors of the Void'),
    'WarCryOnCombat': ('', 'No Tier', 'No DLC'),
    'WarCryOnMultiKill': ("Berzerker's Pauldron", 'Green', 'No DLC'),
    'WardOnLevel': ('Warbanner', 'White', 'No DLC'),
    'WyrmOnHit': ('Sautéed Worms', 'No Tier', 'Alloyed Collective'),
}

EQUIP_INFO: dict[str, tuple[str, ...]] = {
    'BFG': ('Preon Accumulator', 'Normal', 'No DLC'),
    'Blackhole': ('Primordial Cube', 'Normal', 'No DLC'),
    'BossHunter': ("Trophy Hunter's Tricorn", 'Normal', 'Survivors of the Void'),
    'BossHunterConsumed': ("Trophy Hunter's Tricorn (Consumed)", 'Normal', 'Survivors of the Void'),
    'BurnNearby': ('Helfire Tincture', 'Lunar', 'No DLC'),
    'Cleanse': ('Blast Shower', 'Normal', 'No DLC'),
    'CommandMissile': ('Disposable Missile Launcher', 'Normal', 'No DLC'),
    'CrippleWard': ('Effigy of Grief', 'Lunar', 'No DLC'),
    'CritOnUse': ('Ocular HUD', 'Normal', 'No DLC'),
    'DeathProjectile': ('Forgive Me Please', 'Normal', 'No DLC'),
    'DroneBackup': ('The Back-up', 'Normal', 'No DLC'),
    'DroneShockDamage': ('Faulty Conductor', 'Normal', 'Alloyed Collective'),
    'EliteAurelioniteEquipment': ("Aurelionite's Blessing", 'Normal', 'Seekers of the Storm'),
    'EliteBeadEquipment': ('His Spiteful Boon', 'Normal', 'Seekers of the Storm'),
    'EliteCollectiveEquipment': ('Of One Mind', 'Normal', 'Alloyed Collective'),
    'EliteEarthEquipment': ('His Reassurance', 'Normal', 'Survivors of the Void'),
    'EliteFireEquipment': ("Ifrit's Distinction", 'Normal', 'No DLC'),
    'EliteGoldEquipment': ('Coven of Gold', 'Normal', 'No DLC'),
    'EliteHauntedEquipment': ('Spectral Circlet', 'Normal', 'No DLC'),
    'EliteIceEquipment': ('Her Biting Embrace', 'Normal', 'No DLC'),
    'EliteLightningEquipment': ('Silence Between Two Strikes', 'Normal', 'No DLC'),
    'EliteLunarEquipment': ('Shared Design', 'Lunar', 'No DLC'),
    'ElitePoisonEquipment': ("N'kuhana's Retort", 'Normal', 'No DLC'),
    'EliteSecretSpeedEquipment': ('Beyond the Limits', 'Normal', 'Survivors of the Void'),
    'EliteVoidEquipment': ('', 'Normal', 'Survivors of the Void'),
    'EliteYellowEquipment': ('', 'Normal', 'No DLC'),
    'Enigma': ('', 'Normal', 'No DLC'),
    'FireBallDash': ('Volcanic Egg', 'Normal', 'No DLC'),
    'Fruit': ('Foreign Fruit', 'Normal', 'No DLC'),
    'GainArmor': ('Jade Elephant', 'Normal', 'No DLC'),
    'Gateway': ('Eccentric Vase', 'Normal', 'No DLC'),
    'GhostGun': ("Reaper's Remorse", 'Normal', 'No DLC'),
    'GoldGat': ('The Crowdfunder', 'Normal', 'No DLC'),
    'GroundEnemies': ('G-Force Accelerator', 'Normal', 'Alloyed Collective'),
    'GummyClone': ('Goobo Jr.', 'Normal', 'Survivors of the Void'),
    'HealAndRevive': ('Seed of Life', 'Normal', 'Seekers of the Storm'),
    'HealAndReviveConsumed': ('Seed of Life (Consumed)', 'Normal', 'Seekers of the Storm'),
    'IrradiatingLaser': ('Overloading Excavator', 'Normal', 'Survivors of the Void'),
    'Jetpack': ('Milky Chrysalis', 'Normal', 'No DLC'),
    'LifestealOnHit': ('Super Massive Leech', 'Normal', 'No DLC'),
    'Lightning': ('Royal Capacitor', 'Normal', 'No DLC'),
    'LunarPortalOnUse': ('Elegy of Extinction', 'Lunar', 'Survivors of the Void'),
    'LunarPotion': ('', 'Normal', 'No DLC'),
    'Meteor': ('Glowing Meteorite', 'Lunar', 'No DLC'),
    'Molotov': ('Molotov (6-Pack)', 'Normal', 'Survivors of the Void'),
    'MultiShopCard': ('Executive Card', 'Normal', 'Survivors of the Void'),
    'OrbOnUse': ('', 'Normal', 'Survivors of the Void'),
    'OrbitalLaser': ('', 'Normal', 'No DLC'),
    'Parry': ('Deus Ex Machina', 'Normal', 'Alloyed Collective'),
    'PassiveHealing': ('Gnarled Woodsprite', 'Normal', 'No DLC'),
    'QuestVolatileBattery': ('Fuel Array', 'Normal', 'No DLC'),
    'Recycle': ('Recycler', 'Normal', 'No DLC'),
    'Saw': ('Sawmerang', 'Normal', 'No DLC'),
    'Scanner': ('Radar Scanner', 'Normal', 'No DLC'),
    'SoulCorruptor': ('', 'Normal', 'No DLC'),
    'SoulJar': ('Jar of Souls', 'Normal', 'No DLC'),
    'TeamWarCry': ("Gorag's Opus", 'Normal', 'No DLC'),
    'Tonic': ('Spinel Tonic', 'Lunar', 'No DLC'),
    'VendingMachine': ('Remote Caffeinator', 'Normal', 'Survivors of the Void'),
}

STAGE_INFO: dict[str, tuple[str, ...]] = {
    'ancientloft': ('Aphelian Sanctuary', 'Cleansing Center', 'SOTV'),
    'arena': ('Void Fields', 'Cosmic Prison', ''),
    'artifactworld': ("Hidden Realm: Bulwark's Ambry", '', ''),
    'artifactworld01': ("Hidden Realm: Bulwark's Ambry", 'SOTS', ''),
    'artifactworld02': ("Hidden Realm: Bulwark's Ambry", 'SOTS', ''),
    'artifactworld03': ("Hidden Realm: Bulwark's Ambry", 'SOTS', ''),
    'bazaar': ('Hidden Realm: Bazaar Between Time', '', ''),
    'blackbeach': ('Distant Roost', 'Ground Zero', ''),
    'blackbeach2': ('Distant Roost', 'Ground Zero', ''),
    'blackbeachtest': ('', 'SOTV', ''),
    'dampcave': ('', 'SOTV', ''),
    'dampcavesimple': ('Abyssal Depths', 'Tectonic Relics', ''),
    'foggyswamp': ('Wetland Aspect', 'Rehabilitation Zone', ''),
    'frozenwall': ('Rallypoint Delta', "'Contact Light' Survivor Camp", ''),
    'goldshores': ('Hidden Realm: Gilded Coast', '', ''),
    'golemplains': ('Titanic Plains', 'Ground Zero', ''),
    'golemplains2': ('Titanic Plains', 'Ground Zero', ''),
    'golemplains_trailer': ('', 'SOTV', ''),
    'goolake': ('Abandoned Aqueduct', 'Origin of Tar', ''),
    'habitat': ('Treeborn Colony', 'Path of the Protector', 'SOTS'),
    'habitatfall': ('Golden Dieback', 'March of the Fallen', 'SOTS'),
    'helminthroost': ('Helminth Hatchery', "A Brother's Respite", 'SOTS'),
    'itancientloft': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itdampcave': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itfrozenwall': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itgolemplains': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itgoolake': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itmoon': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'itskymeadow': ('The Simulacrum', 'Threat Simulation', 'SOTV'),
    'lakes': ('Verdant Falls', 'Ground Zero', ''),
    'lakesnight': ('Viscous Falls', "Seeker's Setback", 'SOTS'),
    'lemuriantemple': ('Reformed Altar', 'Shadow of the Savior', 'SOTS'),
    'limbo': ('Hidden Realm: A Moment, Whole', '', ''),
    'meridian': ('Prime Meridian', 'Relic of the False Son', 'SOTS'),
    'moon2': ('Commencement', 'Moon of Petrichor V', ''),
    'mysteryspace': ('Hidden Realm: A Moment, Fractured', '', ''),
    'rootjungle': ('Sundered Grove', 'Dormant Locus', ''),
    'shipgraveyard': ("Siren's Call", 'Ship Graveyard', ''),
    'skymeadow': ('Sky Meadow', 'Sprite Fields', ''),
    'snowyforest': ('Siphoned Forest', 'Ground Zero', 'SOTV'),
    'sulfurpools': ('Sulfur Pools', 'Pungent Spring', 'SOTV'),
    'testscene': ('', '', ''),
    'village': ('Shattered Abodes', 'Ground Zero', 'SOTS'),
    'villagenight': ('Disturbed Impact', 'Meter of the Restless', 'SOTS'),
    'voidraid': ('The Planetarium', 'Cell V', 'SOTV'),
    'voidstage': ('Void Locus', 'Cell IIIVIIIIIILVIIIVLVILIVLLLVVVILIVLI', 'SOTV'),
    'wispgraveyard': ('Scorched Acres', 'Wisp Installation', ''),
}
